
version: '2'

networks:
  mvp:

services:

  ca.org1.beesightsoft.com:
    image: hyperledger/fabric-ca:1.2.1
    environment:
    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    - FABRIC_CA_SERVER_CA_NAME=ca-org1
    - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server/ca.org1.beesightsoft.com-cert.pem
    - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server/d6152e9259f632be29ab00fdc5c31b8f38273abadc611fc794c60c9e6132b464_sk
    ports:
    - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
    - ../network_resources/crypto-config/peerOrganizations/org1.beesightsoft.com/ca/:/etc/hyperledger/fabric-ca-server
    container_name: ca_peerOrg1
    networks:
    - mvp

  ca.org2.beesightsoft.com:
    image: hyperledger/fabric-ca:1.2.1
    environment:
    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    - FABRIC_CA_SERVER_CA_NAME=ca-org2
    - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server/ca.org2.beesightsoft.com-cert.pem
    - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server/a267a94ebb0db8dddc2215448409254bd6bafc89b1e20b8f5765209461663d96_sk
    ports:
    - "8054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
    - ../network_resources/crypto-config/peerOrganizations/org2.beesightsoft.com/ca/:/etc/hyperledger/fabric-ca-server
    container_name: ca_peerOrg2
    networks:
    - mvp

  orderer.beesightsoft.com:
    container_name: orderer.beesightsoft.com
    image: hyperledger/fabric-orderer:1.2.1
    environment:
    - ORDERER_GENERAL_LOGLEVEL=debug
    - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
    - ORDERER_GENERAL_GENESISMETHOD=file
    - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
    - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
    - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    networks:
    - mvp
    ports:
    - 7050:7050
    volumes:
    - ../network_resources/config/:/etc/hyperledger/configtx
    - ../network_resources/crypto-config/ordererOrganizations/beesightsoft.com/orderers/orderer.beesightsoft.com/:/etc/hyperledger/msp/orderer
    - ../network_resources/crypto-config/peerOrganizations/org1.beesightsoft.com/peers/peer0.org1.beesightsoft.com/:/etc/hyperledger/msp/peerOrg1
    - ../network_resources/crypto-config/peerOrganizations/org2.beesightsoft.com/peers/peer0.org2.beesightsoft.com/:/etc/hyperledger/msp/peerOrg2

  peer0.org1.beesightsoft.com:
    container_name: peer0.org1.beesightsoft.com
    image: hyperledger/fabric-peer:1.2.1
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_PEER_ID=peer0.org1.beesightsoft.com
    - CORE_LOGGING_PEER=debug
    - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
    - CORE_PEER_LOCALMSPID=Org1MSP
    - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
    - CORE_PEER_ADDRESS=peer0.org1.beesightsoft.com:7051
    # # the following setting starts chaincode containers on the same
    # # bridge network as the peers
    # # https://docs.docker.com/compose/networking/
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_mvp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
    - 7051:7051
    - 7053:7053
    networks:
    - mvp
    volumes:
    - /var/run/:/host/var/run/
    - ../network_resources/crypto-config/peerOrganizations/org1.beesightsoft.com/peers/peer0.org1.beesightsoft.com/msp:/etc/hyperledger/fabric/msp
    - ../network_resources/crypto-config/peerOrganizations/org1.beesightsoft.com/users:/etc/hyperledger/msp/users
    - ../network_resources/config:/etc/hyperledger/configtx
    depends_on:
    - orderer.beesightsoft.com

  peer1.org1.beesightsoft.com:
    container_name: peer1.org1.beesightsoft.com
    image: hyperledger/fabric-peer:1.2.1
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_PEER_ID=peer1.org1.beesightsoft.com
    - CORE_LOGGING_PEER=debug
    - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
    - CORE_PEER_LOCALMSPID=Org1MSP
    - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
    - CORE_PEER_ADDRESS=peer1.org1.beesightsoft.com:7051
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_mvp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    networks:
    - mvp
    ports:
    - 7056:7051
    - 7058:7053
    volumes:
    - /var/run/:/host/var/run/
    - ../network_resources/crypto-config/peerOrganizations/org1.beesightsoft.com/peers/peer1.org1.beesightsoft.com/msp:/etc/hyperledger/fabric/msp
    - ../network_resources/crypto-config/peerOrganizations/org1.beesightsoft.com/users:/etc/hyperledger/msp/users
    - ../network_resources/config:/etc/hyperledger/configtx
    depends_on:
    - orderer.beesightsoft.com

  peer0.org2.beesightsoft.com:
    container_name: peer0.org2.beesightsoft.com
    image: hyperledger/fabric-peer:1.2.1
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_PEER_ID=peer0.org2.beesightsoft.com
    - CORE_LOGGING_PEER=debug
    - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
    - CORE_PEER_LOCALMSPID=Org2MSP
    - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
    - CORE_PEER_ADDRESS=peer0.org2.beesightsoft.com:7051
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_mvp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    networks:
    - mvp
    ports:
    - 8051:7051
    - 8053:7053
    volumes:
    - /var/run/:/host/var/run/
    - ../network_resources/crypto-config/peerOrganizations/org2.beesightsoft.com/peers/peer0.org2.beesightsoft.com/msp:/etc/hyperledger/fabric/msp
    - ../network_resources/crypto-config/peerOrganizations/org2.beesightsoft.com/users:/etc/hyperledger/msp/users
    - ../network_resources/config:/etc/hyperledger/configtx
    depends_on:
    - orderer.beesightsoft.com

  peer1.org2.beesightsoft.com:
    container_name: peer1.org2.beesightsoft.com
    image: hyperledger/fabric-peer:1.2.1
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_PEER_ID=peer1.org2.beesightsoft.com
    - CORE_LOGGING_PEER=debug
    - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
    - CORE_PEER_LOCALMSPID=Org2MSP
    - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
    - CORE_PEER_ADDRESS=peer1.org2.beesightsoft.com:7051
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_mvp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    networks:
    - mvp
    ports:
    - 8056:7051
    - 8058:7053
    volumes:
    - /var/run/:/host/var/run/
    - ../network_resources/crypto-config/peerOrganizations/org2.beesightsoft.com/peers/peer1.org2.beesightsoft.com/msp:/etc/hyperledger/fabric/msp
    - ../network_resources/crypto-config/peerOrganizations/org2.beesightsoft.com/users:/etc/hyperledger/msp/users
    - ../network_resources/config:/etc/hyperledger/configtx
    depends_on:
    - orderer.beesightsoft.com
