# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:
        
  ca1:
    container_name: ca_peerOrg1
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.beesightsoft.com-cert.pem
    ports:
      - "7054:7054"
    volumes:
      - ../../crypto-config/peerOrganizations/org1.beesightsoft.com/ca/:/etc/hyperledger/fabric-ca-server-config

  ca2:
    container_name: ca_peerOrg2
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.beesightsoft.com-cert.pem
    ports:
      - "8054:7054"
    volumes:
      - ../../crypto-config/peerOrganizations/org2.beesightsoft.com/ca/:/etc/hyperledger/fabric-ca-server-config

  orderer.beesightsoft.com:
    container_name: orderer.beesightsoft.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../../config-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../../crypto-config/ordererOrganizations/beesightsoft.com/orderers/orderer.beesightsoft.com/msp:/var/hyperledger/orderer/msp
    - ../../crypto-config/ordererOrganizations/beesightsoft.com/orderers/orderer.beesightsoft.com/tls/:/var/hyperledger/orderer/tls
    - orderer.beesightsoft.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.org1.beesightsoft.com:
    container_name: peer0.org1.beesightsoft.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org1.beesightsoft.com
      - CORE_PEER_ADDRESS=peer0.org1.beesightsoft.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.beesightsoft.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.beesightsoft.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../../crypto-config/peerOrganizations/org1.beesightsoft.com/peers/peer0.org1.beesightsoft.com/msp:/etc/hyperledger/fabric/msp
        - ../../crypto-config/peerOrganizations/org1.beesightsoft.com/peers/peer0.org1.beesightsoft.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org1.beesightsoft.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  peer1.org1.beesightsoft.com:
    container_name: peer1.org1.beesightsoft.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org1.beesightsoft.com
      - CORE_PEER_ADDRESS=peer1.org1.beesightsoft.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.beesightsoft.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.beesightsoft.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../../crypto-config/peerOrganizations/org1.beesightsoft.com/peers/peer1.org1.beesightsoft.com/msp:/etc/hyperledger/fabric/msp
        - ../../crypto-config/peerOrganizations/org1.beesightsoft.com/peers/peer1.org1.beesightsoft.com/tls:/etc/hyperledger/fabric/tls
        - peer1.org1.beesightsoft.com:/var/hyperledger/production

    ports:
      - 8051:7051
      - 8053:7053

  peer0.org2.beesightsoft.com:
    container_name: peer0.org2.beesightsoft.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org2.beesightsoft.com
      - CORE_PEER_ADDRESS=peer0.org2.beesightsoft.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.beesightsoft.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org2.beesightsoft.com:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../../crypto-config/peerOrganizations/org2.beesightsoft.com/peers/peer0.org2.beesightsoft.com/msp:/etc/hyperledger/fabric/msp
        - ../../crypto-config/peerOrganizations/org2.beesightsoft.com/peers/peer0.org2.beesightsoft.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org2.beesightsoft.com:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053

  peer1.org2.beesightsoft.com:
    container_name: peer1.org2.beesightsoft.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org2.beesightsoft.com
      - CORE_PEER_ADDRESS=peer1.org2.beesightsoft.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.beesightsoft.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.beesightsoft.com:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../../crypto-config/peerOrganizations/org2.beesightsoft.com/peers/peer1.org2.beesightsoft.com/msp:/etc/hyperledger/fabric/msp
        - ../../crypto-config/peerOrganizations/org2.beesightsoft.com/peers/peer1.org2.beesightsoft.com/tls:/etc/hyperledger/fabric/tls
        - peer1.org2.beesightsoft.com:/var/hyperledger/production
    ports:
      - 10051:7051
      - 10053:7053

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.beesightsoft.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.beesightsoft.com/peers/peer0.org1.beesightsoft.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.beesightsoft.com/peers/peer0.org1.beesightsoft.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.beesightsoft.com/peers/peer0.org1.beesightsoft.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.beesightsoft.com/users/Admin@org1.beesightsoft.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ../../../chaincode/:/opt/gopath/src/github.com/chaincode
        - ../../crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ../../channel-scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-scripts/
        - ../../config-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/config-artifacts
